import { readdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

/**
 * Serves the clean URLs during development.
 *
 * In production the FastAPI backend maps /faq -> faq.html and /en/ ->
 * en/index.html. Without this the dev server would only answer /faq.html, so
 * every link would have to differ between dev and prod. Ten lines here keep
 * them identical.
 */
function cleanUrls() {
  return {
    name: 'clean-urls',
    configureServer(server) {
      server.middlewares.use((req, _res, next) => {
        const [path, query = ''] = req.url.split('?')
        if (!path.includes('.') && path !== '/') {
          const candidate = path.endsWith('/') ? `${path}index.html` : `${path}.html`
          req.url = candidate + (query ? `?${query}` : '')
        }
        next()
      })
    },
  }
}

export default defineConfig({
  plugins: [react(), cleanUrls()],

  build: {
    rollupOptions: {
      // Multi-page build: each entry becomes its own HTML document in dist/.
      // The marketing pages are generated by scripts/build-site.mjs, which runs
      // first (see package.json) - they carry real content and load no JS at
      // all, which is the entire point for crawlers.
      input: {
        landing: resolve(__dirname, 'index.html'),
        faq: resolve(__dirname, 'faq.html'),
        landingEn: resolve(__dirname, 'en/index.html'),
        faqEn: resolve(__dirname, 'en/faq.html'),
        app: resolve(__dirname, 'app.html'),
      },
    },
  },

  server: {
    port: 5173,
    // All /api calls go to the FastAPI backend. That way the frontend needs no
    // absolute URL and CORS is irrelevant during development.
    proxy: {
      '/api': {
        target: 'http://127.0.0.1:8000',
        changeOrigin: true,
      },
    },
  },
})
